apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-storage
  labels:
    type: local
spec:
  storageClassName: csi-ceph-hdd-gz1
  capacity:
    storage: 2G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/mnt/data'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage-claim
spec:
  storageClassName: csi-ceph-hdd-gz1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G
